
name: npm publish

on:
  push:
    tags:
        - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/setup@v2
        with:
          version: 11
          runtime: node@20
          cache: true
          require-lockfile: true
      - name: 编译 package
        run: pnpm run build
      - name: 发布到npmjs
        env:
          NPM_TPKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ env.NPM_TPKEN != '' }}
        run: |
         npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }} 
         npm publish
